### ISSUE TITLE
Error when installing template Version 4.0: unsupported version number

### ISSUE THREAD

**Issue by psanwald** [hermanekt/zabbix-fail2ban-discovery-#1]
When trying to import the template (for version 4.0), I get the following error within zabbix version 4.0.3 on Ubuntu 18.04:
`Invalid tag "/zabbix_export/version": unsupported version number.`
Installation of template version 3.4 worked just fine.

**Comment by hermanekt** [comment]
Hi Psanwald,

thank for your info. I check import and i have same issue only with **version**. I test this template with zabbix 4.2. I make 2 different version for **4.0 and 4.2**.

Tom
