### ISSUE TITLE
Fail2ban server is Down

### ISSUE THREAD

**Issue by SteepNet** [hermanekt/zabbix-fail2ban-discovery-#19]
hi, all the data about the banned ip is received successfully, but the system always sends that Fail2ban server is Down
CentOS 7
Zabbix 5.2

**Comment by altmas5** [comment]
Hi @SteepNet 
Can you share the output of the following commands executed from the monitored host?
```
zabbix_agentd -t proc.num[python3,,,fail2ban-server]
```

```
zabbix_agentd -t proc.num[fail2ban-server]
```

**Comment by SteepNet** [comment]
zabbix_agentd -t proc.num[python3,,,fail2ban-server]
proc.num[python3,,,fail2ban-server]           [u|0]

zabbix_agentd -t proc.num[fail2ban-server]
proc.num[fail2ban-server]                     [u|0]

**Comment by altmas5** [comment]
Strange, it returns zero, please test with
```bash
zabbix_agentd -t proc.num[,,,fail2ban-server
```

**Comment by SteepNet** [comment]
zabbix_agentd -t proc.num[,,,fail2ban-server]
proc.num[,,,fail2ban-server]                  [u|2]


if I use in the template then the template import error occurs
proc.num[,,,fail2ban-server]

**Comment by SteepNet** [comment]
if I use in the template then the template import error occurs
<key>proc.num[,,,fail2ban-server]</key>

**Comment by altmas5** [comment]
I can see the expression `zabbix_agentd -t proc.num[,,,fail2ban-server]` works on your environment, that should be the one used on the item and trigger, it is strange that it causes a import error. If you modify the template remember to update the item and the trigger with the same expression, both should match.

Can you share the specific error while importing it?

**Comment by hermanekt** [comment]
Environment specific setup.
