### ISSUE TITLE
Error during import of template file on Zabbix 4.2

### ISSUE THREAD

**Issue by ralle12345** [hermanekt/zabbix-fail2ban-discovery-#6]
Hi
I'm having issues importing the template in a freshly installed zabbix 4.2 system. When I import the file the following message appears:

```Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "master_item" is missing.```

Since I'm really new to zabbix I don't know how to debug this problem.

**Comment by hermanekt** [comment]
Hi,

i make quick fix. Can you please redownload template and try to import in to zabbix?

**Comment by ralle12345** [comment]
Hi Tomas,

thanks for your quick fix. Now it imports and works fine on my system.

**Comment by hermanekt** [comment]
Hi,

thank you for test. If you have new idea, what you want, and not find solution give me info. I'm trying find new project for me:)

Tom
